(defvar my-keys-minor-mode-map (make-keymap) "my-keys-minor-mode keymap.")
(define-minor-mode my-keys-minor-mode
  "A minor mode so that my key settings override annoying major modes."
  t nil 'my-keys-minor-mode-map)
(my-keys-minor-mode 1)


(setq cua-enable-cua-keys nil)
(cua-mode t)

(set-kbd-keys cua-global-keymap
  "<C-return>")

(require 'paredit)

(set-kbd-keys my-keys-minor-mode-map
  ("C-p"           . cycle-buffer-permissive)
  ("C-S-p"         . cycle-buffer-backward-permissive)
  ("C-z"           . kill-current-buffer)
  ("C-n"           . save-buffer)
  ("C-f"           . find-file)
  ("C-S-f"         . find-file-other-window)
  ("C-b"           . switch-to-buffer)
  ("M-1"           . delete-other-windows)
  ("M-g"           . goto-line)
  ("C-'"           . duplicate-line)
  ("C-<return>"    . newline-under)
  ("C-\\"          . newline-over)
  ("M-<backspace>" . kill-entire-line)
  ("<f8>"          . undo)
  ("C-("           . kmacro-start-macro)
  ("C-)"           . kmacro-end-macro)
  ("C-*"           . kmacro-end-and-call-macro)
  ("M-@"           . kill-ring-save-buffer)
  ("M-2"           . split-window-vertically)
  ("M-3"           . split-window-horizontally)
  ("C-<tab>"       . hippie-expand)
  ("C-e"           . mark-paragraph)
  ("M-i"           . indent-relative)
  ("C-v"           . kill-ring-save-line)
  ("M-<right>"     . windmove-right)
  ("M-<left>"      . windmove-left)
  ("M-<up>"        . windmove-up)
  ("M-<down>"      . windmove-down)
  ("M-S-<left>"    . winner-undo)
  ("M-S-<right>"   . winner-redo)
  ("C-c C-a"       . align-current)
  ("M-$"           . calc)
  ("C-$"           . quick-calc)
  ("C-S-b"         . switch-to-buffer-other-window)

  ("M-x"   . smex)
  ("C-S-c" . projectile-compile-project)
  ("C-`"   . next-error)
  ("C-#"   . comment-dwim-2)
  ("C-+"   . increment-word)
  ("C-c c" . org-capture)
  ("C-c a" . org-agenda)
  ("C-c l" . org-store-link)
  ("C-c i" . identica)
  ("C-c g" . magit-status)
  ("C-c e" . eshell-command)
  ("C-c m" . notmuch-inbox-unread)
  ("C-a"   . ace-jump-mode)
  ("C-c r" . cua-set-rectangle-mark)
  ("C-c o" . occur)
  ("C-c f" . fullscreen)

  ("S-<up>"        . backward-up-list)
  ("C-S-<up>"      . up-list)
  ("S-<down>"      . down-list)
  ("C-S-<down>"    . backward-down-list)
  ("C-S-<left>"    . backward-to-previous-sexp)
  ("C-S-<right>"   . forward-to-next-sexp)
  ("S-<left>"      . paredit-backward)
  ("S-<right>"     . paredit-forward)
  ("<S-kp-delete>" . kill-sexp)
  ("S-<backspace>" . backward-kill-sexp)
  ("C-S-t"         . transpose-sexps)
  ("M-9"           . insert-parentheses)
  ("M-0"           . delete-window)

  ("<home>"        . move-beginning-of-line)
  ("<end>"         . move-end-of-line)
  ("<C-kp-delete>" . kill-word))
